pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
        commit_message_template: |-
          {{ title }} (#{{ number }})
          {{ body }}
  - name: Automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
    actions:
      merge:
        method: squash
